version: 2

before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

    id: "steampipe"
    binary:
      'steampipe'
    hooks:
      post:
        - cmd: go run ./scripts/stage_embedded_assets --os {{ .Os }} --arch {{ .Arch }} --output ./dist/embedded/{{ .Os }}_{{ .Arch }}
archives:
  - files:
    - none*
    format: zip
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
    - goos: linux
      format: tar.gz

nfpms:
  - id: "steampipe"
    builds: ['steampipe']
    formats:
      - deb
      - rpm
    vendor: "steampipe.io"
    homepage: "https://steampipe.io/"
    maintainer: "Turbot Support <help@turbot.com>"
    description: "Use SQL to instantly query your cloud services (AWS, Azure, GCP and more). Open source CLI. No DB required."
    file_name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    contents:
      - src: ./dist/embedded/{{ .Os }}_{{ .Arch }}/db
        dst: /usr/share/steampipe/embedded/db
        type: tree
        packager: rpm
      - src: ./dist/embedded/{{ .Os }}_{{ .Arch }}/fdw
        dst: /usr/share/steampipe/embedded/fdw
        type: tree
        packager: rpm
    rpm:
      summary: "Use SQL to instantly query your cloud services (AWS, Azure, GCP and more). Open source CLI. No DB required."

# it is necessary to specify the name_template of the snapshot, or else the snapshot gets created with
# two dash(-) which results in a 500 error while downloading
snapshot:
  name_template: '{{ .Version }}'

# snapcrafts:
#   - id: "steampipe"
#     builds: ['steampipe']
#     description: "Use SQL to instantly query your cloud services (AWS, Azure, GCP and more). Open source CLI. No DB required."
#     summary: "Snap package"
#     name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: 'checksums.txt'
release:
  # Visit your project's GitHub Releases page to publish this release.
  draft: true
changelog:
  disable: true
